# Generated by Django 6.0.1 on 2026-01-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetrack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Transport', 'Transport'), ('Subscriptions', 'Subscriptions'), ('Entertainment', 'Entertainment'), ('Other', 'Other')], default='NONE', max_length=50),
        ),
    ]
