# Generated by Django 6.0.1 on 2026-01-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetrack', '0002_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stipend',
            name='month',
            field=models.DateField(),
        ),
    ]
