# Generated by Django 6.0.2 on 2026-02-11 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20)),
                ('remaining_balance', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('start_date', models.DateField()),
                ('currency', models.CharField(default='USD', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(choices=[('Luxury', 'Luxury'), ('subscriptions', 'Subscriptions'), ('groceries', 'Groceries'), ('transport', 'Transport'), ('other', 'Other')], max_length=50)),
                ('date', models.DateField()),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('paid', models.BooleanField(default=True)),
                ('income_stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='budgetrack.incomestream')),
            ],
        ),
    ]
